### Data Types

In [1]:
import torch
x = torch.rand(5, 5)
print(x)
print(torch.__version__)

tensor([[0.6799, 0.2797, 0.3841, 0.6674, 0.0758],
        [0.7443, 0.5401, 0.1327, 0.5454, 0.9595],
        [0.7006, 0.7810, 0.8063, 0.4000, 0.9670],
        [0.9103, 0.0971, 0.5680, 0.0644, 0.3570],
        [0.5634, 0.1203, 0.7328, 0.0422, 0.5257]])
1.12.1+cu113


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#get dimensions of the tensor
scalar.ndim

0

In [ ]:
#get item out of the tensor
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
import torch
vector = torch.tensor([7, 7])
#vector dimension
print(vector.ndim)
#vector size
vector.shape

1


torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR = torch.tensor([[[[[[1,2,3]]]]]])
TENSOR.ndim

6

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 1, 1, 3])

### Random tensors

Why random tensors?
Randoms tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers --> look at data --> update random numbers --> look at data --> repeat

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of shape/size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2978, 0.6858, 0.5683, 0.5609],
        [0.9041, 0.6158, 0.6818, 0.3285],
        [0.2428, 0.0020, 0.7977, 0.0608]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (R, G, B)
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
# torch.rand(size=(3,4,4)) = torch.rand(3,4,4)

In [ ]:
### Zeros and ones

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

https://pytorch.org/docs/stable/tensors.html

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, #datatype of tensor
                               device=None,        #by default CPU, can be CUDA
                               requires_grad=False) #tracking gradients or not
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)



1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`


In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1101, 0.6400, 0.4491, 0.7978],
        [0.7797, 0.8237, 0.8018, 0.9326],
        [0.2521, 0.5921, 0.6512, 0.9052]])

In [ ]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1101, 0.6400, 0.4491, 0.7978],
        [0.7797, 0.8237, 0.8018, 0.9326],
        [0.2521, 0.5921, 0.6512, 0.9052]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multipilcation

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])


In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Division
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10) #Generally better to use normal Python operators

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication'
2. Matrix multiplication (dot product)
*matmul(tensor1, tensor2)
*@

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, **2**) @ (**3**, 2)` won't work
* `(2, **3**) @ (**3**, 2)` will work
* `(3, **2**) @ (**2**, 3)` will work
2. The resulting matrix has the shape of the **outer dimension**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

Graphic explanation of matrix multiplication: http://matrixmultiplication.xyz


In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor) 
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.38 ms, sys: 0 ns, total: 4.38 ms
Wall time: 4.53 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 190 µs, sys: 0 ns, total: 190 µs
Wall time: 155 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2, 3], 
                         [4, 5, 6]])
tensor_B = torch.tensor([[7, 8, 9], 
                         [10, 11, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm == torch.matmul (it's an alias for matmul)


RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose.**
A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T # T stands for transpose
tensor_B, tensor_B.T.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]), torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: \ntensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: \ntensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: \n{tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: 
tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: 
tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: 
torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [18]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires 
# a tensor of float dtype 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [14]:
# Find the position in tensor that has the minimum value with argmin()
# Returns -> index position of target tensor where the minimum value occurs
x.argmin() 

tensor(0)

In [20]:
x[0]

tensor(1)

In [19]:
# Find the position in tensor that has the minimum value with argmin()
# Returns -> index position of target tensor where the minimum value occurs
x.argmax()

tensor(9)

In [21]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [31]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [32]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9) # size has to match (9*1=10)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [35]:
# Change the view
# Z shares memory with x so changing z changes x
z = x.view(1,9)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [44]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [54]:
# Squeeze
x_squeezed = x_reshaped.squeeze()
x_reshaped, x_squeezed

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
# Unsqueeze
x_squeezed, x_squeezed.unsqueeze(dim=0)

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [62]:
# torch.permute - rearranges tensor dimension in a specified order
x1 = torch.rand(224, 224, 3) # [height, width, colour_channels]
x_permuted = x1.permute(2, 0, 1) # [ colour_channels, width, height]
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NUmPy

In [66]:
# Create a tensor
import torch
x  = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [67]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
# Let's index on the middle bracket [dim=1]
x[0][0]

tensor([1, 2, 3])

In [76]:
# Let's index on the most inner bracket [last bracket]
x[0, 2, 2]

tensor(9)

In [77]:
# You can also use ":" to get all of a target dim
x[:, :, 2] 

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor, want in NumPy -> `torch.Tensor.numpy()`

In [82]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1, 8)
tensor = torch.from_numpy(array) # when converting numpy -> pytorch, 
array, tensor                    # numpy datatype is reflected in pytorch

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [83]:
# Change the value of the array
array = array + 1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [84]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # datatype also reflected
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again..`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

Extra resources for reproducibility: https://pytorch.org/docs/stable/notes/randomness.html

https://en.wikipedia.org/wiki/Random_seed

In [87]:
import torch
# Set the random seed
RANDOM_SEED = 42
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)
random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything cool

### 1. Getting a GPU
* Use Google Colab for free GPU
* Use your own GPU - takes a little bit of setup and requires an investment
* Use cloud computing - GCP, AWS, Azure


In [1]:
!nvidia-smi # Tesla T4 GPU

Mon Oct 17 21:34:00 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's good practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

E. g. run on GPU if available, else defualt to CPU

In [3]:
# Setup a device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors and models on the GPU

The reason we want our tensors/models on the GPU is because of greater speed of computations.

In [6]:
# Create a tensor (default on the GPU)
tensor = torch.tensor([1, 2, 3], device='cpu')
tensor.device

device(type='cpu')

In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [9]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [10]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])